config/routes.rb
Rails.application.routes.draw do 

  root to: "blogs#index"
  devise_for :users, controllers:{
          sessions: 'users/sessions',
          registrations: 'users/registrations'}

  
  resources :blogs
  
  #get 'blogs/destroy/:id' => 'blogs#destroy'
  get 'users/index'
  get 'users/new'
  get 'users/show'
  get 'users/edit'
  post 'users/update'
  get 'users/create'
  post 'users/store'
  get 'users/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
validates :title, :content, presence: true, length: { in: 3..30 }

def self.search(search) 
  if search
      patterns = search.split(/[ ,　]/)
      sql_body = ''
      patterns.each do | pattern |
        sql_body += ' and ' unless sql_body.blank?
        sql_body += " content like '%#{pattern}%' "
      end
      sql = "select * from blogs where #{sql_body} order by id desc"
      blog_ids = Blog.find_by_sql(sql)
      ids = []
      blog_ids.each do |qi|
        ids.push(qi.id)
      end
      where(:id => ids)
    else
    Blog.all #全て表示。
  end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :find_id, only: [:show, :edit, :update, :destroy]
  
  def index
    if params[:search].present?
      @blogs = Blog.search(params[:search])
    else
    #@blogs = Blog.all
    @blogs = Blog.paginate(page: params[:page],per_page: 10)
    end
  end

  def new
    @blog = Blog.new
    @user = current_user
  end

  def create
    permitted_params = params.require(:blog).permit(:id, :title, :content,:user_id)
    @blog = Blog.new (permitted_params)
    if @blog.save
      flash[:notice] = "新規登録しました！"
      redirect_to blog_path(@blog.id)
    else
      render 'new'
   end
  end

  def show
  end

  def edit
  end

  def update
   if @blog.update(params.require(:blog).permit(:title, :content))
    flash[:notice] = "更新しました！"
    redirect_to blogs_path
   else 
     render 'edit'
   end
  end

  def destroy  
    @blog.destroy
    redirect_to action: :index
  end

  def find_id
    @blog = Blog.find(params[:id])
    @user = current_user
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<h1>ブログ編集</h1>
<%=form_for @blog do |db| %>
    <p>
    <%= db.label(:title,"タイトル")%>
    <%= db.text_field :title%>
    </p>
    <p>
    <%= db.label :content, "記事の内容" %>
    <%= db.text_area :content %>
    </p>
    <%= db.submit "更新" %>
<th><%= link_to "一覧", blogs_path %></th>
<th><%= link_to "詳細へもどる", blog_path %></th>
<% end %>

app/views/blogs/index.html.erb
<!-- filename:index.html.erb -->
<body>
<h1>ブログ一覧</h1> <!-- 見出し -->

<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<!-- 検索 -->
<%= form_tag blogs_path, :method => 'get' do %>
	<p>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag "検索", :name => nil %>
	</p>
<% end %>

<!-- 表の設定 -->
<%= will_paginate %>
<!-- 外枠の太さと罫線の表示形式を指定している -->
<table border = "1" rules = "all">
    <tr>
    <!-- 見出し1 -->
        <!--th style = "text-align:center">ID</th-->
        <!-- 見出し2 -->
        <th style = "text-align:center">タイトル</th>
        <!-- 見出し3 -->
        <th style = "text-align:center">記事の内容</th>
        <!-- 見出し4 -->
        <th style = "text-align: center">作成日時></th>
        <!-- 見出し5 -->
        <th style = "text-align: center">投稿者></th>
    </tr>
    
    <!--blogモデルに紐づくblogsテーブルから全てのデータを取得-->
    <% @blogs.order(created_at:"DESC").each do |blog| %>
        <tr>
            <!--td style="text-align:center"><%=  blog.id%></td-->
            <td style = "text-align:left"><%= link_to blog.title ,blog_path(blog.id)%> </td>
            <td style = "text-align:left"><%= blog.content %> </td>
            <td style = "text-align:left"><%= blog.created_at%> </td>
            
            <!--Usernameの取得と無名時の処理-->
            <%  @user_name = User.find_by(id: blog.user_id)%>
            <%if @user_name%>
            <td style = "text-align:left"><%= @user_name.user_name%></td>
            <%else%>
            <td style = "text-align:left">未記入</td>
            <%end%> 
        
          </tr>
    <% end %>
    
</table>
<!--th><%= link_to"新規投稿", new_blog_path%></t-->
<%= will_paginate %>
</body>

app/views/blogs/new.html.erb
<h1>新規投稿</h1>
<%= form_for @blog do |f| %>
    <p>
    <!--%= f.label :user_id, current_user.user_name %-->
    <%= f.hidden_field :user_id, value: @user.id %>
    </p>
    <p>
    <%= f.label(:title, "タイトル") %>
    <%= f.text_field :title %>
    </p>
    <p>
    <%= f.label :content, "記事の内容" %>
    <%= f.text_area :content %>
    </p>
    <% if @blog.errors.any? %>
        <p>エラー!</p>
        <%= render 'layouts/error_messages', model: f.object %>
    <% end %>
    <%= f.submit "登録" %>
<th><%= link_to "一覧", blogs_path %></th>
  <% end %>

app/views/blogs/show.html.erb
<h1>詳細確認</h1>
<table border = "1" rules = "all">
    <tr>
        <th>タイトル</th>
        <td><%= @blog.title %></td>
    </tr>
    <tr>
        <th>記事の内容</th>
        <td><%= @blog.content %></td>
    </tr>
    
    <tr>
    <th>投稿日</th>
    <td><%= @blog.created_at %></td>
    </tr>
    <tr>
    <th>最終更新日</th>
    <td><%= @blog.updated_at %></td>
    </tr>
    <tr>
    <th>投稿者</th>
    <!--Usernameの取得と無名時の処理-->
    <%  @user_name = User.find_by(id: @blog.user_id)%>
    <%if @user_name%>
    <td style = "text-align:left"><%= @user_name.user_name%></td>
    <%else%>
    <td style = "text-align:left">未記入</td>
    <%end%> 

    </table>
    <% if user_signed_in? and @blog.user_id.to_s == @user.id.to_s %>
<th><%= link_to "編集", edit_blog_path %></th>
<th><%= button_to "削除", blog_path(@blog.id), {method: :delete ,data: {confirm: "本当に削除しますか？"} }%></th>
<th><%= link_to "削除", blog_path(@blog.id), method: :delete,data: {confirm: "本当に削除しますか？"}  %></th>
<% end %>
<th><%= link_to "一覧", blogs_path %></th>

app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>